config/routes.rb
Kanban::Application.routes.draw do
  get "tasks/create"
  get "tasks/update"
  get "tasks/destroy"
  devise_for :users do
	  root to: "devise/sessions#new"
  end

  resources :home
  resources :projects do
	  resources :tasks
  end

  

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :tasks, dependent: :destroy

	default_scope order(:name)

	validates :name, presence: true
	validates :desc, presence: true
	validates :desc, length: { maximum:20 }

	def to_param
		"#{id}-#{name}".parameterize
	end
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project

	validates :name, presence: true

	scope :todo, -> { where(task_type: "todo") }
	scope :doing, -> {  where(task_type: "doing") }
	scope :done,  -> { where(task_type: "done") }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
	  home_index_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!

  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!

  def index
	  @projects = current_user.projects
  end

  def show
	  @project = current_user.projects.find(params[:id])
	  @task = Task.new
	  @todo = @project.tasks.todo
	  @doing = @project.tasks.doing
	  @done = @project.tasks.done
  end

  def new
	  @project = Project.new
  end

  def create
	  @project = current_user.projects.build(project_params)

	  if @project.save	
		redirect_to projects_path, notice: "Created new project \"#{@project.name}\""
	  else
		render :new
	  end
  end

  def edit
  end

  def update
  end

  def destroy
  end

private

  def project_params
	params.require(:project).permit(:name,:desc)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
 
  before_filter :authenticate_user!
  before_filter :get_project

  def create
	  @task = @project.tasks.build(task_params)

	  if @task.save
		  redirect_to @project, notice: "New task created under #{@task.task_type.upcase}"
	  else
		  redirect_to @project, alert: "Oops! An error has occurred while creating new task"
	  end
  end

  def update
  end

  def destroy
  end

private
  def get_project
	@project = current_user.projects.find(params[:project_id])
  end

  def task_params
	  params.require(:task).permit(:name, :task_type)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def t(page_title=nil)
		content_for :title do
			if page_title.nil?
				"Kanban PH"
			else
				"Kanban PH | #{page_title}"
			end
		end
	end

	def g(user, klazz, options={})
		options[:default] = 'https://assets.github.com/images/gravatars/gravatar-140.png'
		if !user.nil?
			gravatar_image_tag(user.email, title:user.email, class:klazz, gravatar: options)
		else
			gravatar_image_tag('default', title:'default', class:klazz, gravatar: options)
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_profile.html.erb
<div class='profile-block'>
	<div class='pull-left'>
		<%= g(current_user, 'img-circle', size: 128) %> &nbsp; 
		<span class="badge badge-info"> <%= current_user.email %> </span>
	</div>

	<div class="clearfix"></div>
</div>

<div class='menu-block top20'>
	<strong> What do you want to do? </strong>
	
	<ul class="unstyled top10">
		<li> <%= link_to "Edit Profile", edit_user_registration_path %> </li>
		<li> <%= link_to "View Projects", projects_path %> </li>
		<li> <%= link_to "Create Project", new_project_path %> </li>
	</ul>
</div>

app/views/home/index.html.erb
<%= t('Home') %>

<% if user_signed_in? %>
	<div class="row">
		<div class="span4">
			<%= render "profile" %>
		</div>

		<div class="span8">
			<div class='content-block'>
				Displayed here are graphs, statistical reports about the projects
			</div>

			<div class='top20' id="annual" style="width:500px;height:350px">
			</div>
		</div>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title> <%= yield :title %> </title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
		<div class="row">
			<div class="span12">
				<div class='pull-left'>
					<h1> Kanban PH <small> project management made easy! </small> </h1>
				</div>

				<div class='pull-right top20'>
					<%= link_to "<i class='icon icon-refresh icon-white'></i>".html_safe, home_index_path, class:"btn btn-inverse btn-large", title:"Home" %> &nbsp;
					<%= link_to "Logout", destroy_user_session_path, method: :delete, class:"btn btn-large btn-danger", confirm: "Are you sure?" %>
				</div>

				<div class="clearfix"></div>

				<hr />
			</div>
		</div>

		<% if notice %>
			<div class="alert alert-success">
				<%= notice %>
			</div>
		<% end %>

		<% if alert %>
			<div class="alert alert-error">
				<%= alert %>
			</div>
		<% end %>

		<div class="row">
			<div class="span12">
				<%= yield %>
			</div>
		</div>
	</div>

</body>
</html>

app/views/projects/_project.html.erb
<%= div_for project, class:"bottom20" do %>
	<div class='pull-right'>
		<%= g(nil, 'img-circle', size: 96) %>
	</div>

	<div class="left20">
		<h3> <%= project.name %> <small> <%= project.desc %> </small> </h3>

		<strong class="italic"> This project started <%= distance_of_time_in_words(Time.now, project.created_at) %> ago. </strong>

		<div class="project-block bottom20 well" style="width:500px">
			<%= link_to "View Project", project, class:"btn btn-primary" %>
			&nbsp;
			<%= link_to "Delete Project", project, method: :delete, class:"btn btn-danger", confirm:"Delete this project?" %>
		</div>
	</div>

	<div class="clearfix"></div>
<% end %>

<hr />

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<%= t('Projects') %>

<div class="row">
	<div class="span4">
		<%= render "home/profile" %>
	</div>

	<div class="span8">
		<ul class="nav nav-tabs">
			<li class="active"> <a href="#projects" data-toggle="tab">Projects(<%=@projects.size%>)</a></li>
			<li> <a href="#activities" data-toggle="tab">Activities</a> </li>
		</ul>

		<div class="tab-content">
			<div class="tab-pane active" id="projects">
				<p class='italic'> Note: Click a specific project to toggle options </p>


				<%= render(partial:"project",collection:@projects) || "<div class='alert alert-error'>No projects yet.</div>".html_safe %>
			</div>

			<div class="tab-pane" id="activities">
				your public activities
			</div>
		</div>

	</div>
</div>

app/views/projects/new.html.erb
<%= t('New Project') %>

<div class="row">
	<div class="span4">
		<%= render "home/profile" %>
	</div>

	<div class="span8">
		<p class="lead"> Create a Project </p>

		<div class="top20">
			<%= form_for @project do |f| %>

				<% unless @project.errors.empty? %>
					<div class="alert alert-error">
						<div>
							<h2 style="color:red"> <%= pluralize @project.errors.size, "error" %> found. </h2>
							<ul class="unstyled">
								<% @project.errors.full_messages.each do |err| %>
									<li> <%= err %> </li>
								<% end %>
							</ul>
						</div>
					</div>
				<% end %>

				<%= f.label :name %>
				<%= f.text_field :name, placeholder: "Enter project name" %>

				<br />

				<%= f.label :desc %>
				<%= f.text_area :desc, rows: 3, placeholder: "Enter a description for this project" %>

				<br />

				<%= f.submit "Create", class:"btn" %>
			<% end %>
		</div>
	</div>
</div>

app/views/projects/show.html.erb
<%= t(@project.name) %>

<div class="row">
	<div class="span4">
		<%= render "home/profile" %>
	</div>

	<div class="span8">
		<div class="span12" style="margin-left:-70px">

		<p class="lead"> Kanban Board for <b> <%= @project.name.upcase %> </b> </p>

		<div class="span3">
			<div class="task-block">
				<h3> <blockquote style="color:#666"> TODO <small> <%= link_to "add todo task", "#", class:"task-link", data: {toggle:"modal",target:"#taskModal",task:"todo"} %> </small> </blockquote> </h3>
				<hr />

				<div class='top10'>
					<%= render partial:"tasks/task", collection:@todo %>
				</div>

			</div>
		</div>

		<div class="span3">
			<div class="task-block">
				<h3> <blockquote style="color:#666"> DOING <small> <%= link_to "add doing task", "#", class:"task-link", data: {toggle:"modal",target:"#taskModal",task:"doing"} %> </small> </blockquote> </h3>
				<hr />

				<div class='top10'>
					<%= render partial:"tasks/task", collection:@doing %>
				</div>

			</div>
		</div>

		<div class="span3">
			<div class="task-block">
				<h3> <blockquote style="color:#666"> DONE <small> <%= link_to "add done task", "#taskModal", class:"task-link", data: {toggle:"modal",task:"done"} %> </small> </blockquote> </h3>
				<hr />

				<div class='top10'>
					<%= render partial:"tasks/task", collection:@done %>
				</div>
	
			</div>
		</div>
	</div>
</div>

<!-- Modal -->
<div id="taskModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	 <div class="modal-header">
		  <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
		  <h3 id="myModalLabel"> Add Task for <span id="taskType"></span>  </h3>
	  </div>

	  <div class="modal-body">
		  <%= form_for [@project,@task] do |f| %>
			<%= f.label :name %>
			<%= f.text_field :name, placeholder: "Enter task name", required:"required" %>
			<%= f.hidden_field :task_type %>

			<br />

		        <div class="modal-footer">
			   <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	          	   <button type="submit" class="btn btn-primary">Save changes</button>
	    	        </div>
				
		  <% end %>
	  </div>
</div>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/tasks/_task.html.erb
<%= div_for task, class:"well bottom10" do |t| %>
	<%= t.name %>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>